version: "3.9"

services:
  web:
    build: .
    container_name: django_taskforgelab
    restart: always
    env_file:
      - .env
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}  # ⚠️ Agora ele puxa direto do .env
      DB_PORT: "5432"
      SECRET_KEY: ${SECRET_KEY}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - taskforge_network  # Conectar ao banco na mesma rede

networks:
  taskforge_network:
    external: true  # Usar a rede já existente (não criar outra)
